name: TheCleaner
main: net.krinsoft.thecleaner.Cleaner
version: maven-version-number
author: krinsdeath

load: startup

commands:
  cleanup:
    aliases: [clean]
    description: Clean up the entities in your server's worlds
    usage: /<command>
  sysstat:
    aliases: [system, stat]
    description: Show pertinent information about the JVM and host OS
    usage: /<command>
  performance:
    aliases: [perf, perform]
    description: Checks the performance of the server over the last day.
    usage: |
      /<command>                - Check performance over the last day.
      /<command> [days]         - Check performance over the specified period of days.
      /<command> -r|--reset     - Reset performance statistics.
permissions:
  thecleaner.performance:
    description: Allows the user to check the server's performance metrics.
    default: op
  thecleaner.system:
    description: Allows the user to see system information via /sysstat.
    default: op
  thecleaner.all:
    description: Allows the user to flag all worlds for cleaning.
    default: op
  thecleaner.debug:
    description: Allows the user to toggle debug mode.
    default: op
  thecleaner.broadcast:
    description: Allows the user to broadcast cleanups to the server.
    default: op
  thecleaner.info:
    description: Allows the user to list information about the world's entities.
    default: op
  thecleaner.verbose:
    description: Adds more detailed messages to the cleaning process.
    default: op
  thecleaner.force:
    description: Allows the user to flag all entities for cleaning. Excludes players.
    default: op
  thecleaner.vehicle:
    description: Allows the user to flag vehicles for cleaning.
    default: op
  thecleaner.painting:
    description: Allows the user to flag paintings for cleaning.
    default: op
  thecleaner.monster:
    description: Allows the user to flag monsters for cleaning. Excludes bosses.
    default: op
  thecleaner.animal:
    description: Allows the user to flag animals for cleaning.
    default: op
  thecleaner.watermob:
    description: Allows the user to flag water mobs for cleaning.
    default: op
  thecleaner.golem:
    description: Allows the user to flag golems for cleaning.
    default: op
  thecleaner.pet:
    description: Allows the user to flag pets for cleaning.
    default: op
  thecleaner.villager:
    description: Allows the user to flag villagers for cleaning.
    default: op
  thecleaner.dragon:
    description: Allows the user to flag the ender dragon for cleaning.
    default: op
  thecleaner.item:
    description: Allows the user to flag items older than 60 seconds for cleaning.
    default: op
  thecleaner.frame:
    description: Allows the user to flag item frames for cleaning.
    default: op
  thecleaner.radius:
    description: Allows the user to specify that only entities within the given radius are cleaned.
    default: op
  thecleaner.projectile:
    description: Allows the user to flag orphaned and glitched projectiles for cleaning.
    default: op
  thecleaner.explosive:
    description: Allows the user to flag explosives for cleaning.
    default: op
  thecleaner.report:
    description: Allows a user to print a detailed report of the cleaning.
    default: op
  thecleaner.world.*:
    description: Allows the user to clean entities on all loaded worlds.
    default: op
  thecleaner.*:
    description: Sets all Cleaner nodes to true
    default: op
    children:
      thecleaner.performance: true
      thecleaner.system: true
      thecleaner.all: true
      thecleaner.debug: true
      thecleaner.broadcast: true
      thecleaner.info: true
      thecleaner.verbose: true
      thecleaner.force: true
      thecleaner.vehicle: true
      thecleaner.painting: true
      thecleaner.monster: true
      thecleaner.animal: true
      thecleaner.watermob: true
      thecleaner.golem: true
      thecleaner.pet: true
      thecleaner.villager: true
      thecleaner.dragon: true
      thecleaner.item: true
      thecleaner.frame: true
      thecleaner.radius: true
      thecleaner.projectile: true
      thecleaner.explosive: true
      thecleaner.report: true
      thecleaner.world.*: true